GET http://127.0.0.1:3333/expenses HTTP/1.1


###

POST http://127.0.0.1:3333/expenses HTTP/1.1
content-type: application/json

{
    "date":{{$timestamp}},
    "description":"MacBook Pro 13",
    "amount":{{$randomInt 100000 5000000}}
}

###

DELETE http://127.0.0.1:3333/expenses/5 HTTP/1.1

###

